version: '3'
services:
  simpleapp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: simplewebapp:2.0
    container_name: simplewebapp
    ports: 
      - "5000:5000"
    restart: always
    networks:
      - webnet

networks:
  webnet: