apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simplewebapp.fullname" . }}
  labels:
    {{- include "simplewebapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simplewebapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simplewebapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
