apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: simplewebapp:2.0
        ports:
        - containerPort: 5000
